name: 🚀 Deploy website on push master
on: 
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
    - uses: ./.github/actions/sshrsync-action
      with:
          privkey: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          hostname: "example.com"
          options: "--exclude=.git --exclude=node_modules --exclude=.git*"
          serverpath: "var/www/socialhouse.top/htdocs"        
          protocolo: SFTP
          port: 22