name: 'Generate and deploy'
#Funciona mas não envia os arquivo pro server
on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ master ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Generate and deploy website
        uses: ronvanderheijden/hugo-rsync-deployment@master
        env:
          VPS_DEPLOY_KEY: ${{ secrets.FTP_PASSWORD }}
          VPS_DEPLOY_USER: ${{ secrets.FTP_USERNAME }}
          VPS_DEPLOY_HOST: ${{ secrets.FTP_HOST }}
          VPS_DEPLOY_DEST: /var/www/socialhouse.top/
        with:
          hugo-arguments: '--minify'
          rsync-arguments: '--archive --compress --xattrs --delete'